# Generated by Django 5.2.7 on 2025-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_image_file_alter_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text="Âge de l'utilisateur")),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text="Genre de l'utilisateur", max_length=10)),
                ('estimated_salary', models.IntegerField(help_text='Salaire estimé')),
                ('will_purchase', models.BooleanField(help_text='Prédiction: va-t-il acheter?')),
                ('confidence', models.FloatField(help_text='Niveau de confiance (0-1)')),
                ('probability_purchase', models.FloatField(help_text="Probabilité d'achat (0-1)")),
                ('probability_no_purchase', models.FloatField(help_text='Probabilité de non-achat (0-1)')),
                ('model_name', models.CharField(help_text='Nom du modèle utilisé', max_length=100)),
                ('model_accuracy', models.FloatField(help_text='Précision du modèle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
